=== Marvbudd/shoebox/app/resource/accessions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:simpleType name="LastNameType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="married" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="lastType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="type" use="optional" type="LastNameType" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:element name="first" type="xs:string" />
	<xs:element name="last" type="lastType" />
	<xs:element name="position" type="xs:string" />
	<xs:complexType name="personType">
		<xs:sequence>
			<xs:element ref="first" />
			<xs:element ref="last" maxOccurs="unbounded" />
			<xs:element ref="position" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="sourceType">
		<xs:all>
			<xs:element name="person" type="personType" />
			<xs:element name="received" type="dateType" />
		</xs:all>
	</xs:complexType>
	<xs:element name="accession" type="xs:string" />
	<xs:element name="link" type="xs:string" />
	<xs:complexType name="entryType">
		<xs:sequence>
			<xs:element name="ref" type="xs:string" />
			<xs:element name="starttime" type="xs:string" minOccurs="0" />
			<xs:element name="duration" type="xs:string" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="playlistType">
		<xs:sequence>
			<xs:element name="entry" type="entryType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="locationType">
		<xs:sequence>
			<xs:element name="detail" type="xs:string" minOccurs="0" maxOccurs="3" />
			<xs:element name="city" type="xs:string" minOccurs="0" />
			<xs:element name="state" type="xs:string" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>
	<xs:element name="location" type="locationType" />
	<xs:element name="year" type="xs:gYear" />
	<xs:element name="month">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Jan" />
				<xs:enumeration value="Feb" />
				<xs:enumeration value="Mar" />
				<xs:enumeration value="Apr" />
				<xs:enumeration value="May" />
				<xs:enumeration value="Jun" />
				<xs:enumeration value="Jul" />
				<xs:enumeration value="Aug" />
				<xs:enumeration value="Sep" />
				<xs:enumeration value="Oct" />
				<xs:enumeration value="Nov" />
				<xs:enumeration value="Dec" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="day" type="xs:string" />
	<xs:complexType name="dateType">
		<xs:all>
			<xs:element ref="year" />
			<xs:element ref="month" minOccurs="0" />
			<xs:element ref="day" minOccurs="0" />
		</xs:all>
	</xs:complexType>
	<xs:element name="description" type="xs:string" />
	<xs:element name="type">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="photo" />
				<xs:enumeration value="tape" />
				<xs:enumeration value="video" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:complexType name="itemType">
		<xs:sequence>
			<xs:element ref="link" />
			<xs:element name="person" type="personType" maxOccurs="unbounded" />
			<xs:element ref="description" />
			<xs:element ref="accession" />
			<xs:element ref="type" />
			<xs:element name="date" type="dateType" />
			<xs:element ref="location" minOccurs="0" maxOccurs="2"/>
			<xs:element name="playlist" type="playlistType" minOccurs="0" />
			<xs:element name="source" type="sourceType" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="categories" type="xs:string" use="optional" />
	</xs:complexType>
	<!--the root element-->
	<xs:element name="accessions">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="item" type="itemType" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Marvbudd/shoebox/app/resource/accessions.xml
<accessions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="accessions.xsd"><item><link>BRKE053.jpg</link><person>
			<first>Erma Mae</first>
			<last>Barker</last>
			<last type="married">Budd</last>
		</person><description>Erma is about the third row from the front right of center.</description><accession>1080</accession><type>photo</type><date>
			<year>1924</year>
		</date><location>
			<detail>Indiana Academy</detail>
			<city>Cicero</city>
			<state>IN</state>
		</location><playlist>
      <entry>
        <ref>BUDC19951120a.mp3</ref>
        <starttime>00:00:00.0</starttime>
        <duration>00:01:30.0</duration>
      </entry>
    </playlist><source>
			<person>
				<first>Erma Mae</first>
				<last>Barker</last>
				<last type="married">Budd</last>
			</person>
			<received>
				<month>Aug</month>
				<year>1999</year>
			</received>
		</source></item><item><link>BRKP009.jpg</link><person>
			<first>Fairy Belle</first>
			<last>Hicks</last>
			<last type="married">Barker</last>
		</person><person>
			<first>Peter</first>
			<last>Barker</last>
		</person><person>
			<first>Erma Mae</first>
			<last>Barker</last>
			<last type="married">Budd</last>
		</person><person>
			<first>William Ervin</first>
			<last>Barker</last>
		</person><person>
			<first>Robert Edward</first>
			<last>Barker</last>
		</person><person>
			<first>Otto Franklin</first>
			<last>Barker</last>
		</person><person>
			<first>Clarence Alfred</first>
			<last>Barker</last>
		</person><description>This picture was taken when Erma came to New Albany to teach the church school with her brothers in it. Peter found out Erma would be teaching school and he was the chairman of the church school board. So he said "come down and teach our school". Erma could live at home and they needed a teacher.</description><accession>1163</accession><type>photo</type><date>
			<year>1925</year>
		</date><location>
			<city>New Albany</city>
			<state>IN</state>
		</location><playlist>
			<entry>
				<ref>3-1990Nov241921.mp4</ref>
				<starttime>00:35:52.0</starttime>
				<duration>00:00:32.0</duration>
			</entry>
		</playlist><source>
			<person>
				<first>Erma Mae</first>
				<last>Barker</last>
				<last type="married">Budd</last>
			</person>
			<received>
				<month>Aug</month>
				<year>1999</year>
			</received>
		</source></item><item><link>BUDT011.jpg</link><person>
			<first>Beverly Joanne</first>
			<last>Budd</last>
			<last type="married">Brown</last>
		</person><person>
			<first>Landle Merle</first>
			<last>Budd</last>
		</person><person>
			<first>Theodore Ronald</first>
			<last>Budd</last>
		</person><person>
			<first>Philip Joseph</first>
			<last>Pfeiffer</last>
		</person><person>
			<first>Milton Julius</first>
			<last>Pfeiffer</last>
		</person><person>
			<first>Donald Dean</first>
			<last>Campbell</last>
		</person><person>
			<first>Clara May</first>
			<last>Schmoe</last>
			<last type="married">Budd</last>
		</person><person>
			<first>Ethel Cora</first>
			<last>Budd</last>
			<last type="married">Pfeiffer</last>
		</person><person>
			<first>Eleanor May</first>
			<last>Pfeiffer</last>
			<last type="married">Hight</last>
			<position>in Ethel&amp;apos;s arms</position>
		</person><person>
			<first>Doris Ann</first>
			<last>Campbell</last>
			<last type="married">Vaught</last>
		</person><person>
			<first>Lavee</first>
			<last>Campbell</last>
			<last type="married">Douglas</last>
		</person><person>
			<first>Carl E</first>
			<last>Campbell</last>
		</person><person>
			<first>Wilda Alice</first>
			<last>Budd</last>
			<last type="married">Campbell</last>
			<last type="married">Cowell</last>
			<last type="married">Allen</last>
		</person><person>
			<first>Thomas Oliver</first>
			<last>Budd</last>
		</person><person>
			<first>Vernon</first>
			<last>Budd</last>
		</person><person>
			<first>Clara May</first>
			<last>Rose</last>
			<last type="married">Budd</last>
		</person><person>
			<first>Chester</first>
			<last>Budd</last>
		</person><person>
			<first>Erma Mae</first>
			<last>Barker</last>
			<last type="married">Budd</last>
		</person><person>
			<first>Carl E</first>
			<last>Campbell Jr</last>
		</person><description>Guessing on Wilda&amp;apos;s family. Picture was labelled "Aunts, Uncles, Grandparents, cousins, Mother and Father, brothers and sisters.</description><accession>45</accession><type>photo</type><date>
			<month>Nov</month>
			<year>1929</year>
		</date><location>
			<city>Crawfordsville</city>
			<state>IN</state>
		</location><playlist>
      <entry>
        <ref>3-1990Nov241854.mp4</ref>
        <starttime>00:10:52.0</starttime>
        <duration>00:00:15.0</duration>
      </entry>
    </playlist><source>
			<person>
				<first>Chester</first>
				<last>Budd</last>
			</person>
			<received>
				<month>Aug</month>
				<year>1999</year>
			</received>
		</source><source>
			<person>
				<first>Donald</first>
				<last>Campbell</last>
			</person>
			<received>
				<day>20</day>
				<month>Jun</month>
				<year>1992</year>
			</received>
		</source></item><item><link>ZNTM003b.jpg</link><person>
			<first>Mike</first>
			<last>Daley</last>
		</person><person>
			<first>Kate</first>
			<last>Barker</last>
			<last type="married">Daley</last>
			<last type="married">Streepey</last>
		</person><person>
			<first/>
			<last>unknown</last>
		</person><person>
			<first>Betty</first>
			<last>Streepey</last>
		</person><person>
			<first/>
			<last>Streepey</last>
		</person><person>
			<first>Mary</first>
			<last>Zintz</last>
			<last type="married">Barker</last>
		</person><person>
			<first/>
			<last>unknown</last>
		</person><description>Clifford married Venice and had Betty. Identities unconfirmed. Unknowns are related to Venice.</description><accession>1127</accession><type>photo</type><date>
			<year>1939</year>
		</date><location>
			<city>Toledo</city>
			<state>OH</state>
		</location><source>
			<person>
				<first>JoAnn</first>
				<last>Oldom</last>
				<last type="married">Carmickle</last>
			</person>
			<received>
				<year>2003</year>
				<month>Nov</month>
				<day>25</day>
			</received>
		</source></item><item><link>BUDC19951120a.mp3</link><person>
			<first>Chester</first>
			<last>Budd</last>
		</person><person>
			<first>Erma Mae</first>
			<last>Barker</last>
			<last type="married">Budd</last>
		</person><description>End of summary continued from BRKE19951119b, Indiana Academy, meeting Erma Barker. Teaching elementary school. Transition from union printing to work at EMC. Working at Journal Era until May 1944 when they moved to La Sierra college. Working at Riverside, and the Union college in 1949-1953. Then AUC and back to Andrews University.</description><accession>83</accession><type>tape</type><date>
			<day>20</day>
			<month>Nov</month>
			<year>1995</year>
		</date><location>
			<city>Vernon</city>
			<state>VT</state>
		</location><source>
			<person>
				<first>Marvin Earl</first>
				<last>Budd</last>
			</person>
			<received>
				<day>20</day>
				<month>Nov</month>
				<year>1995</year>
			</received>
		</source></item><item><link>9-1996Mar251006.mp4</link><person>
			<first>Samuel</first>
			<last>Peterson</last>
		</person><person>
			<first>Estella</first>
			<last type="married">Peterson</last>
		</person><description>TODO</description><accession>1645</accession><type>video</type><date>
			<month>Mar</month>
			<year>1996</year>
			<day>25</day>
		</date><location>
			<detail>Hayden Cemetery</detail>
			<city>Jennings County</city>
			<state>IN</state>
		</location><source>
			<person>
				<first>Marvin Earl</first>
				<last>Budd</last>
			</person>
			<received>
				<day>23</day>
				<month>Dec</month>
				<year>2015</year>
			</received>
		</source></item></accessions>
